theme: osuny
_merge: deep
params:
  search:
    active: true
  menu:
    primary:
      level_2:
        summary:
          active: true
  summary:
    position: hero
  breadcrumb:
    position: after-hero
  posts:
    index:
      layout: grid
  organizations:
    single:
      backlinks: true
  persons:
    single:
      backlinks: true
  home:
    head:
      title: site
  logo:
    header: ""
    footer: ""